// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/editor": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/reset-password": {
    params: {};
  };
  "/account": {
    params: {};
  };
  "/api/auth/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/editor" | "/login" | "/reset-password" | "/account" | "/api/auth/*";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/editor.tsx": {
    id: "routes/editor";
    page: "/editor";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/reset-password.tsx": {
    id: "routes/reset-password";
    page: "/reset-password";
  };
  "routes/account.tsx": {
    id: "routes/account";
    page: "/account";
  };
  "routes/api.auth.$.ts": {
    id: "routes/api.auth.$";
    page: "/api/auth/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/editor": typeof import("./app/routes/editor.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/reset-password": typeof import("./app/routes/reset-password.tsx");
  "routes/account": typeof import("./app/routes/account.tsx");
  "routes/api.auth.$": typeof import("./app/routes/api.auth.$.ts");
};